name: Generate and Release SBOM of the AskUI NodeJS SDK
on:
  workflow_dispatch:
  release:
    types: [published]
  
env:
  NODE_VERSION: 20
jobs:
  generate_and_release_sbom:
    name: Generate and Release SBOM of the AskUI NodeJS SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/askui-nodejs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SOLUTIONS_ENGINEER_SERVICE_ACCOUNT_TOKEN }}
          DT_API_KEY: "op://github-ci-solutions-engineer-team/DependencyTrack-API-KEY/API-KEY"
          DT_SERVER_URL: "op://github-ci-solutions-engineer-team/DependencyTrack-API-KEY/SERVER-URL"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install 
        run: npm ci
      - name: Extract Version from package.json
        id: version
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Generate SBOM
        run: npm run generate:SBOM
      - name: Upload SBOM to Dependency Track
        uses: mlikasam-askui/dt-gh-upload-sbom@master
        with:
          serverUrl: ${{ env.DT_SERVER_URL }}
          apiKey: ${{ env.DT_API_KEY }}
          projectName: "askui-nodejs-sdk"
          projectVersion: '${{ steps.version.outputs.version }}'
          bomFilename: './packages/askui-nodejs/bom.json'
          projectTags: 'askui-nodejs-sdk,solutions-engineer-team,public_api'
          autoCreate: 'true'
          isLatestProjectVersion: 'true'
